### PR TITLE
Add `url` as a library

### PR DESCRIPTION
**Pull request by macobo**
We can do some url-based analysis/changes based on this.

## Checklist

-   [ ] Updated Settings section in README.md, if settings are affected
-   [ ] Jest tests

### CODE REVIEW

**Review by Twixes — APPROVED** [review]

**Comment by mariusandra** [comment]
Could we also add `url` to package.json to explicitly pin it to a version? It's now installed randomly by `aws-sdk` and that could drop on any upgrade.

**Comment by Twixes** [comment]
As far as I understand this is the [Node `url` module](https://nodejs.org/api/url.html), is it not? `url` from `npm` is a polyfill for browsers.

**Comment by macobo** [comment]
AFAIK, that was my own takeaway as well based on https://nodejs.org/api/url.html

**Comment by mariusandra** [comment]
Ah, then please ignore me :)

**Pull request merged**
