### PR TITLE
Kafka e2e tests

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- It's green!

## Checklist

-   [ ] Updated Settings section in README.md, if settings are affected
-   [ ] Jest tests

### CODE REVIEW

**Comment by mariusandra** [comment]
Making progress:

image

**Comment by mariusandra** [comment]
Almost there...
image

**Comment by mariusandra** [comment]
And now we're here:

image

The github action will still probably fail though.

**Comment by mariusandra** [comment]
Ready for a review @Twixes ! I'd be super happy to merge this into #34 ASAP... and then also wrap that one up and get it live.

I'm going to make a final todo list now... 😄🤞

**Review by Twixes — APPROVED** [review]
Great work getting this to work in CI 😄 Docker all the way down

**Pull request merged**
