### PR TITLE
Update ts-node for M1 support with workers

### LINKED ISSUE #370: yarn start:dev is hanging (running on M1)
I can start the plugin server on M1 with `yarn build; WORKER_CONCURRENCY=2 yarn start:dist`
but
Running `yarn start:dev` hangs with this output:

[INFO] 06:56:59 ts-node-dev ver. 1.1.1 (using ts-node ver. 9.1.1, typescript ver. 4.1.2)
[MAIN] 06:57:05 ⚡ @posthog/plugin-server v0.20.1
[MAIN] 06:57:05 ℹ️ 2 workers, 10 tasks per worker
[MAIN] 06:57:05 ✅ Connected to Redis!
[MAIN] 06:57:05 🚶 Connected to job queue producer "graphile"
[MAIN] 06:57:05 🔁 @posthog/mmdb is 48 days old, which is more than the staleness threshold of 45 days, refreshing in the background...
[MAIN] 06:57:05 ⏳ Downloading GeoLite2 database from PostHog servers...
[MAIN] 06:57:05 🪗 Decompressed GeoLite2-City-2021-03-23.mmdb.br from 21.9 MB into 63.1 MB
[MAIN] 06:57:05 🗺 Starting internal MMDB server...
[MAIN] 06:57:05 👂 Internal MMDB server listening on port 58270
[MAIN] 06:57:05 ⏰ Starting scheduling service...
[MAIN] 06:57:06 ✅ Downloaded GeoLite2-City-2021-03-23.mmdb of 21.9 MB
[MAIN] 06:57:07 💾 Saved GeoLite2-City-2021-03-23.mmdb into the database
[MAIN] 06:57:07 🪗 Decompressed GeoLite2-City-2021-03-23.mmdb from 21.9 MB into 63.1 MB
[MAIN] 06:57:07 💉 Injected fresh @posthog/mmdb

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- Resolves #370 
- After these changes, the workers started again for me on my M1 Air. 
- I was now running NodeJS 16.3, but I'd expect it to work on other versions.
- The TS update required some changes to a few places. Probably `!!` would have done the trick as well. Not sure why it errored there though, as `value` had `undefined` as one of its type options, so 🤷 

## Checklist

-   [ ] Updated Settings section in README.md, if settings are affected
-   [ ] Jest tests

### CODE REVIEW

**Comment by neilkakkar** [comment]
The undefined weirdness could be because:

```

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.2.0

YOUR TYPESCRIPT VERSION: 4.3.2

Please only submit bug reports when using the officially supported version.
```

**Comment by mariusandra** [comment]
Good point. I bumped all the eslint packages as well.

**Comment by mariusandra** [comment]
This is trickier than I expected. I need to upgrade `ts-node` to v27 to fix those TS errors, but that requires at least NodeJS 14.15.0.

I have 14.5.0 installed and personally have no problem upgrading, but what about all our clients? What nodejs version are they running? I remember when we created the plugin server, a lot of customers said they had to explicitly upgrade their node versions to 14 for it to work. What frustrations will this change bring if they now have to upgrade to 14.15?

I hence limited `ts-node` to the latest v26. 🤞

**Comment by alexkim205** [comment]
Yes! Tested the branch locally and it works beautifully.

**Review by alexkim205 — APPROVED** [review]

**Comment by mariusandra** [comment]
Great! Feel free to merge ;)

**Review by Twixes — APPROVED** [review]

**Pull request merged**
