### PR TITLE
Don't "ALTER TABLE person UPDATE"

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

`ALTER TABLE person UPDATE` is ran on every person-updating event and, due to the way ClickHouse works, that causes a drastic increase of load in terms of `person` parts. This contributed to the ClickHouse crash on 100% plugin server ingestion. Before rolling out plugin server ingestion, we need to solve person updates differently.
This PR simply eliminates the update query – not great for data integrity… but also the way Python ingestion is anyway…
Long term, we need a better solution.

### CODE REVIEW

**Comment by mariusandra** [comment]
So this obviously breaks postgres parity... and is it really true no props are updated for persons in CH? 🤔

**Comment by Twixes** [comment]
Please do crosscheck how it's done in the Python version, but that's how it appears to be from my inspection!

**Comment by mariusandra** [comment]
Now we just `insert` when changing any properties, just like the python ingestion does. The `ReplacingMergeTree` will take care of eliminating the old rows eventually... and in queries we'll just select `max(_timestamp)`...

**Review by Twixes — COMMENTED** [review]
This should work

**Pull request merged**
