### PR TITLE
Capture db query errors to sentry

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- Experimenting...

## Checklist

-   [ ] Updated Settings section in README.md, if settings are affected
-   [ ] Jest tests

### CODE REVIEW

**Comment by yakkomajuri** [comment]
What's the status here? Any reason not to try on Cloud?

**Comment by mariusandra** [comment]
I think this didn't catch some specific errors I was looking at (could have been bigquery or s3 uploads), so I forgot about it. Alternatively, I think some errors this caught just raised yet another error for the same thing in sentry.

Thus I just forgot about this :). Feel free to pick it up or merge if you think it could help!

**Comment by yakkomajuri** [comment]
Closing in favor of #486

**Comment by yakkomajuri** [comment]
Oh wait wrong PR

**Comment by yakkomajuri** [comment]
Nevertheless will close this actually. Spring cleaning in progress.

**Pull request closed without merging**
